// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package user

import (
	"time"
)

type User struct {
	ID        string
	Username  string
	Password  []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}
